version: "3.8"

services:

  #
  # xion-rehearsal-3
  #

  gentx:
    image: burntnetwork/xion:0.3.4
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/gentx.sh
    environment:
      MONIKER: "🔥 ahi.burnt.com 🔥"
      CHAIN_ID: "xion-rehearsal-3"
      GENESIS_AMOUNT: "1000000000000uxion"
      KEYNAME: "ahi.burnt.com"
      KEYRING_BACKEND: "file"
      KEYRING_PASSPHRASE: "SuperSecretPassphrase42069"
      MNEMONIC: ""  # giant dynamic salmon...
      VAL_COMMISSION_MAX_RATE: "1.00"
      VAL_COMMISSION_MAX_CHANGE_RATE: "1.00"
      VAL_COMMISSION_RATE: "1.00"
      VAL_DETAILS: "https://burnt.com"
      VAL_IDENTITY: "FFBBF0F93A1E9190"
      VAL_SECURITY_CONTACT: "daemon@burnt.com"
      VAL_WEBSITE: "https://burnt.com"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-3:/tmp/testnet

  collect-gentxs:
    image: burntnetwork/xion:0.3.4
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/collect-gentxs.sh
    environment:
      MONIKER: "burnt"
      CHAIN_ID: "xion-rehearsal-3"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-3:/tmp/testnet

  validate-genesis:
    image: burntnetwork/xion:0.3.4
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/validate-genesis.sh
    environment:
      MONIKER: "burnt"
      CHAIN_ID: "xion-rehearsal-3"
    volumes:
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-3:/tmp/testnet

  generate-hashes:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/generate-hashes.sh
    volumes:
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-3:/tmp/testnet

  verify-hashes:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/verify-hashes.sh
    volumes:
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-rehearsal-3:/tmp/testnet

  #
  # xion-testnet-1
  #

  validate-genesis-xion-testnet-1:
    image: burntnetwork/xion:0.1.0
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/validate-genesis.sh
    environment:
      MONIKER: "burnt"
      CHAIN_ID: "xion-testnet-1"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-testnet-1:/tmp/testnet

  generate-hashes-xion-testnet-1:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/generate-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-testnet-1:/tmp/testnet

  verify-hashes-xion-testnet-1:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/verify-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./testnets/xion-testnet-1:/tmp/testnet
